In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('googleplaystore.csv')
df.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
5664,"realestate.com.au - Buy, Rent & Sell Property",HOUSE_AND_HOME,3.8,14657,Varies with device,"1,000,000+",Free,0,Everyone,House & Home,"July 16, 2018",Varies with device,Varies with device
389,free video calls and chat,COMMUNICATION,4.2,594728,Varies with device,"50,000,000+",Free,0,Everyone,Communication,"July 19, 2018",7.3(800241),4.4 and up
3818,"BuzzFeed: News, Tasty, Quizzes",NEWS_AND_MAGAZINES,4.3,131028,13M,"5,000,000+",Free,0,Teen,News & Magazines,"July 30, 2018",5.38,4.4 and up
8987,DW Espanol,NEWS_AND_MAGAZINES,NaN,0,5.8M,100+,Free,0,Everyone,News & Magazines,"June 5, 2018",1.0,4.2 and up
1489,Real estate court auction information site - H...,HOUSE_AND_HOME,NaN,10,4.2M,"10,000+",Free,0,Everyone,House & Home,"August 2, 2018",1.2,4.3 and up
3673,Free TV series,VIDEO_PLAYERS,3.7,400,7.2M,"100,000+",Free,0,Teen,Video Players & Editors,"May 28, 2018",v1.0.3,4.0.3 and up
4618,Don't touch my phone,TOOLS,3.8,21943,2.3M,"5,000,000+",Free,0,Everyone,Tools,"October 19, 2016",30,2.3 and up
1599,US Mission - buy gourmet movie KTV,LIFESTYLE,3.8,6554,76M,"500,000+",Free,0,Teen,Lifestyle,"June 20, 2018",9.4.2,4.1 and up
3830,Yandex.Transport,MAPS_AND_NAVIGATION,4.0,126282,Varies with device,"10,000,000+",Free,0,Everyone,Maps & Navigation,"July 30, 2018",5.7,4.1 and up
22,Superheroes Wallpapers | 4K Backgrounds,ART_AND_DESIGN,4.7,7699,4.2M,"500,000+",Free,0,Everyone 10+,Art & Design,"July 12, 2018",2.2.6.2,4.0.3 and up

#### Steps to typically follow with every dataset
1. Data Cleaning
2. Exploratory Data Analysis (EDA)
3. Feature Engineering

In [4]:
### Basic dataset information gathering and observation
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

(10841, 13)

In [5]:
### Checking for any missing values in your dataset
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [ ]:
## Checking for the missing values in the Type, Content Rating and Current Ver columns
df[df['Type'].isnull()]
df[df['Content Rating'].isnull()]
df[df['Current Ver'].isnull()]
## Checking for the missing values in the Genres column
df[df['Genres'].isnull()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
15,Learn To Draw Kawaii Characters,ART_AND_DESIGN,3.2,55,2.7M,"5,000+",Free,0,Everyone,Art & Design,"June 6, 2018",NaN,4.2 and up
1553,Market Update Helper,LIBRARIES_AND_DEMO,4.1,20145,11k,"1,000,000+",Free,0,Everyone,Libraries & Demo,"February 12, 2013",NaN,1.5 and up
6322,Virtual DJ Sound Mixer,TOOLS,4.2,4010,8.7M,"500,000+",Free,0,Everyone,Tools,"May 10, 2017",NaN,4.0 and up
6803,BT Master,FAMILY,NaN,0,222k,100+,Free,0,Everyone,Education,"November 6, 2016",NaN,1.6 and up
7333,Dots puzzle,FAMILY,4.0,179,14M,"50,000+",Paid,$0.99,Everyone,Puzzle,"April 18, 2018",NaN,4.0 and up
7407,Calculate My IQ,FAMILY,NaN,44,7.2M,"10,000+",Free,0,Everyone,Entertainment,"April 3, 2017",NaN,2.3 and up
7730,UFO-CQ,TOOLS,NaN,1,237k,10+,Paid,$0.99,Everyone,Tools,"July 4, 2016",NaN,2.0 and up
10342,La Fe de Jesus,BOOKS_AND_REFERENCE,NaN,8,658k,"1,000+",Free,0,Everyone,Books & Reference,"January 31, 2017",NaN,3.0 and up

#### Handling Missing Values Column by Column and cleaning the dataset

In [11]:
### 1. Starting with reviews
### First we would want to check if all values in the reviews column though str are numeric in nature
### Also Reviews don't have any missing values to start with
print(df['Reviews'].str.isnumeric().sum())

10840

In [12]:
### Throwing the error for the different field in the Reviews row
df['Reviews'].astype(int)

ValueError: invalid literal for int() with base 10: '3.0M'

In [13]:
### 10840 out of 10841 means one of the fields is not numeric by nature
### hence we need to find out how
### we can text by trying to convert all the fields to int and see what throws the error or check which is not numeric
df[~df['Reviews'].str.isnumeric()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [14]:
### Now you have the decision of converting to thousands or droping the record completely
## But first lets make a copy of the dataset and work on the copy from now on
df_copy=df.copy()

In [15]:
#### Drop just that row from the dataset
df_copy=df_copy.drop(index=[10472])

###
df_copy[~df_copy['Reviews'].str.isnumeric()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [16]:
#### Convert the reviews feature to integer
df_copy['Reviews']=df_copy['Reviews'].astype(int)

In [17]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            10840 non-null  str
 5   Installs        10840 non-null  str
 6   Type            10839 non-null  str
 7   Price           10840 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 1.2 MB

In [18]:
#### Handling the Size feature next
### Size has both M-Megabyte and k-Kilobyte. Hence we need to convert to one particular datatype 
df_copy['Size'].unique()

<StringArray>
[  '19M',   '14M',  '8.7M',   '25M',  '2.8M',  '5.6M',   '29M',   '33M',
  '3.1M',   '28M',
 ...
  '467k',  '157k',   '44k',  '676k',   '67k',  '552k',  '885k', '1020k',
  '582k',  '619k']
Length: 461, dtype: str

##### Thought Process: Cleaning the Size Column

`Step 1: Inspect the raw data first`

The Google Play Store Size column typically looks like this:
['19M', '14M', '8.7M', '25M', '2.8M', '512k', '3.0M', 'Varies with device', ...]

*Key observations from this inspection:*

Values are strings, not numbers.
Sizes are mixed units: M (Megabytes) and k (Kilobytes).
There's a non-numeric category: "Varies with device" — this isn't missing data (NaN), but it's not a usable number either. You need a strategy for it.

This inspection step is critical — you should never blindly write a conversion function before knowing what all the unique values look like. Skipping this is how you get silent bugs or NaN explosions later.

`Step 2: Decide on target unit`:

*Reasoning*: You need one consistent unit to make the column numeric and comparable. You have two choices:

Convert everything to `KB (kilobytes)` — avoids fractional values since M → K is multiplying by 1024 (or 1000).
Convert everything to `MB` — keeps numbers smaller/more interpretable, but K → M creates decimals (e.g., 512k → 0.5M).

Either is valid. I'll standardize to KB here since it avoids introducing decimals from the smaller unit, but the logic is symmetric if you prefer MB.


`Step 3: Decide what to do with "Varies with device"`

This is a feature engineering decision, not just cleaning:

Option A: Convert to`NaN` and impute later (e.g., median size, or median size grouped by Category).
Option B: Create a separate binary flag column (Size_Varies = 1) before nulling it out — because "varies with device" might itself carry signal (e.g., apps with device-dependent size might behave differently, like games vs. utility apps).

I'd recommend Option B — it preserves information rather than discarding it.`

`Step 4: Write the conversion function`

In [19]:
def convert_size(size):
    if size == 'Varies with device':
        return np.nan
    elif size.endswith('M'):
        return float(size[:-1]) * 1024   # MB -> KB
    elif size.endswith('k'):
        return float(size[:-1])          # already in KB
    else:
        return np.nan  # catch any unexpected format

`Why write it as a function with explicit branches instead of a one-liner regex replace?`

It's easier to read and debug.
The else: return np.nan branch acts as a safety net — if the dataset has some unexpected format you didn't anticipate during Step 1, it won't crash your pipeline; it'll just surface as a NaN you can investigate.

In [20]:
### Step 5: Apply it and create the flag column first
df_copy['Size_Varies'] = (df_copy['Size'] == 'Varies with device').astype(int)

In [22]:
df_copy.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_Varies
8798,Dr. Doug's Tips,BOOKS_AND_REFERENCE,4.0,22,34M,"1,000+",Free,0,Everyone,Books & Reference,"September 1, 2016",1.1,2.3 and up,0
3481,Content Transfer,PRODUCTIVITY,4.7,19302,7.2M,"5,000,000+",Free,0,Everyone,Productivity,"June 28, 2018",3.5.12,4.0.3 and up,0
9523,Train Racing Games 3D 2 Player,GAME,4.3,192374,56M,"10,000,000+",Free,0,Everyone,Racing,"January 9, 2018",Varies with device,5.0 and up,0
3419,LINE Launcher,PERSONALIZATION,4.4,733838,21M,"10,000,000+",Free,0,Everyone,Personalization,"June 29, 2018",2.4.25,4.0.3 and up,0
8578,Shaggy's DM Assistant,PRODUCTIVITY,NaN,0,Varies with device,5+,Free,0,Everyone,Productivity,"January 14, 2018",Varies with device,Varies with device,1
4716,W Pro - Weather Forecast & Animated Weather Maps,WEATHER,3.8,11,2.9M,500+,Paid,$1.99,Everyone,Weather,"April 23, 2018",1.0,4.1 and up,0
5442,WGT Golf Game by Topgolf,SPORTS,4.3,148083,57M,"10,000,000+",Free,0,Everyone,Sports,"July 24, 2018",1.42.2,4.1 and up,0
9084,Cute Dolphin Keyboard,PERSONALIZATION,4.5,237,6.4M,"10,000+",Free,0,Everyone,Personalization,"July 30, 2018",1.279.13.93,4.0.3 and up,0
3699,Video.Guru - Video Maker,VIDEO_PLAYERS,4.6,36969,27M,"1,000,000+",Free,0,Everyone,Video Players & Editors,"August 6, 2018",1.137.22,4.3 and up,0
4165,Ramfer - CNC Lathe G-code Tool,PRODUCTIVITY,3.4,5,11M,100+,Paid,$2.99,Everyone,Productivity,"September 26, 2016",2,3.2 and up,0

`Why do this?`

Notice something interesting.

Originally the information was stored as text:

`Varies with device`

But that text really represents a condition:

Does the app have a fixed size?

Yes or No.

By creating Size_Varies, you've transformed a text category into a binary feature (0 or 1), which is much easier for many machine learning algorithms to use.

In [23]:
### After this step you can apply conversion
df_copy['Size'] = df_copy['Size'].apply(convert_size)

In [24]:
df_copy.sample(5)
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  str
 6   Type            10839 non-null  str
 7   Price           10840 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
 13  Size_Varies     10840 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 1.2 MB

In [25]:
df_copy[['Size', 'Size_Varies']].sample(10)

         Size  Size_Varies
3802      NaN            1
9381   3481.6            0
3410      NaN            1
8251   5939.2            0
5882   3788.8            0
7740  26624.0            0
640    5120.0            0
1626   6963.2            0
2151  24576.0            0
2603      NaN            1

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [27]:
### Step 7: Handle the resulting missing values
df_copy['Size'].isnull().sum()

np.int64(1695)

In [ ]:
## All varies with device column are now converted to NaN and have 1 in the Size_Varies column
df_copy[df_copy['Size'].isnull()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_Varies
37,Floor Plan Creator,ART_AND_DESIGN,4.1,36639,NaN,"5,000,000+",Free,0,Everyone,Art & Design,"July 14, 2018",Varies with device,2.3.3 and up,1
42,Textgram - write on photos,ART_AND_DESIGN,4.4,295221,NaN,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",Varies with device,Varies with device,1
52,Used Cars and Trucks for Sale,AUTO_AND_VEHICLES,4.6,17057,NaN,"1,000,000+",Free,0,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device,Varies with device,1
67,Ulysse Speedometer,AUTO_AND_VEHICLES,4.3,40211,NaN,"5,000,000+",Free,0,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device,Varies with device,1
68,REPUVE,AUTO_AND_VEHICLES,3.9,356,NaN,"100,000+",Free,0,Everyone,Auto & Vehicles,"May 25, 2018",Varies with device,Varies with device,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10713,My Earthquake Alerts - US & Worldwide Earthquakes,WEATHER,4.4,3471,NaN,"100,000+",Free,0,Everyone,Weather,"July 24, 2018",Varies with device,Varies with device,1
10725,Posta App,MAPS_AND_NAVIGATION,3.6,8,NaN,"1,000+",Free,0,Everyone,Maps & Navigation,"September 27, 2017",Varies with device,4.4 and up,1
10765,Chat For Strangers - Video Chat,SOCIAL,3.4,622,NaN,"100,000+",Free,0,Mature 17+,Social,"May 23, 2018",Varies with device,Varies with device,1
10826,Frim: get new friends on local chat rooms,SOCIAL,4.0,88486,NaN,"5,000,000+",Free,0,Mature 17+,Social,"March 23, 2018",Varies with device,Varies with device,1
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,1

### Step 1: What's the problem we're trying to solve?

Suppose your dataset looks like this:

App	Category	Size_KB
WhatsApp	Communication	25000
Gmail	Communication	30000
Zoom	Communication	NaN
Candy Crush	Games	85000
Subway Surfers	Games	90000
Temple Run	Games	NaN

Notice that Zoom and Temple Run have missing sizes.

A simple approach would be:

```python
df['Size_KB'] = df['Size'].fillna(0)
```

This fills every missing value with the overall median.

But is that reasonable?

Communication apps tend to be much smaller than games. Giving both the same replacement value could distort the data.

A better idea is:

`Fill each missing size using the median size within its own category.`

In [31]:
df_copy['Size'] = df_copy['Size'].fillna(
    df_copy.groupby('Category')['Size'].transform('median')
)

In [32]:
df_copy.info()
df_copy['Size'].isnull().sum()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            10840 non-null  float64
 5   Installs        10840 non-null  str
 6   Type            10839 non-null  str
 7   Price           10840 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
 13  Size_Varies     10840 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 1.2 MB

np.int64(0)

- This is the general pattern for any "messy mixed-unit string column": inspect unique values → choose a target unit → explicitly decide how to treat non-numeric categories → write an explicit conversion function with a safety-net else branch → verify → impute.

In [33]:
df_copy.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_Varies
1981,Flow Free,GAME,4.3,1295625,11264.0,"100,000,000+",Free,0,Everyone,Puzzle,"April 11, 2018",4.0,4.1 and up,0
10708,Custos F.O.,BUSINESS,NaN,0,9932.8,1+,Free,0,Everyone,Business,"June 20, 2018",4.1.0,4.1 and up,0
6312,BJ Bridge Free (2018),GAME,3.9,20,4915.2,"10,000+",Free,0,Everyone,Card,"May 21, 2018",6.2-lite,4.0 and up,0
5353,Amazon for Tablets,SHOPPING,4.0,141584,22528.0,"10,000,000+",Free,0,Teen,Shopping,"July 31, 2018",16.14.0.850,4.4 and up,0
6480,BM Assets,FINANCE,NaN,6,10137.6,500+,Free,0,Everyone,Finance,"October 25, 2016",1.1,2.3.3 and up,0
9981,PokeType - Dex,FAMILY,4.6,36813,33792.0,"500,000+",Free,0,Everyone,Entertainment,"May 1, 2018",4.2.0,4.1 and up,0
7724,CQ-Alert,COMMUNICATION,NaN,3,8294.4,500+,Free,0,Everyone,Communication,"November 28, 2016",5.5.0,4.0 and up,0
2902,Square InPic - Photo Editor & Collage Maker,PHOTOGRAPHY,4.4,635846,14336.0,"50,000,000+",Free,0,Everyone,Photography,"May 23, 2018",4.2.14,4.0 and up,0
10495,HD Themes Toyota Cruiser70,PERSONALIZATION,NaN,0,15360.0,100+,Free,0,Teen,Personalization,"October 3, 2016",1.0,2.3.3 and up,0
1960,Metal Soldiers 2,GAME,4.4,153381,40960.0,"10,000,000+",Free,0,Teen,Action,"June 18, 2018",1.11.2,4.1 and up,1