In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:
df=pd.read_csv('googleplaystore.csv')
df.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4285,KIM KARDASHIAN: HOLLYWOOD,GAME,4.3,1017408,34M,"10,000,000+",Free,0,Teen,Adventure,"July 16, 2018",9.2.0,4.0 and up
3635,Weather Radar Widget,WEATHER,4.3,18194,3.2M,"1,000,000+",Free,0,Everyone,Weather,"June 28, 2017",1.7.7,3.0 and up
5795,Axe Champs! Wars,GAME,5.0,8,25M,50+,Free,0,Everyone,Arcade,"June 26, 2018",1.1,4.1 and up
8892,dt.se,NEWS_AND_MAGAZINES,3.1,124,12M,"10,000+",Free,0,Everyone,News & Magazines,"June 29, 2018",4.9.0,4.1 and up
2962,MLB At Bat,SPORTS,4.2,82882,Varies with device,"5,000,000+",Free,0,Everyone,Sports,"July 30, 2018",Varies with device,Varies with device
10427,IKORO FH App Rosenheim,FAMILY,NaN,22,29M,"1,000+",Free,0,Everyone,Education,"February 6, 2018",1.10.0.0,2.3.3 and up
10226,Video Downloader for FB : Video Download with ...,VIDEO_PLAYERS,4.5,1060,3.2M,"100,000+",Free,0,Everyone,Video Players & Editors,"December 20, 2017",2.1,4.0 and up
2902,Square InPic - Photo Editor & Collage Maker,PHOTOGRAPHY,4.4,635846,14M,"50,000,000+",Free,0,Everyone,Photography,"May 23, 2018",4.2.14,4.0 and up
7989,The CW TV app,FAMILY,3.2,24,4.8M,"5,000+",Free,0,Everyone,Entertainment,"July 28, 2018",1.1,3.2 and up
5438,3D Tennis,SPORTS,4.2,1008012,13M,"50,000,000+",Free,0,Everyone,Sports,"December 5, 2017",1.7.7,2.1 and up

#### Steps to typically follow with every dataset
1. Data Cleaning
2. Exploratory Data Analysis (EDA)
3. Feature Engineering

In [26]:
### Basic dataset information gathering and observation
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

(10841, 13)

In [27]:
### Checking for any missing values in your dataset
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

#### Handling Missing Values Column by Column and cleaning the dataset

In [28]:
### 1. Starting with reviews
### First we would want to check if all values in the reviews column though str are numeric in nature
### Also Reviews don't have any missing values to start with
print(df['Reviews'].str.isnumeric().sum())

10840

In [29]:
### Throwing the error for the different field in the Reviews row
df['Reviews'].astype(int)

ValueError: invalid literal for int() with base 10: '3.0M'

In [30]:
### 10840 out of 10841 means one of the fields is not numeric by nature
### hence we need to find out how
### we can text by trying to convert all the fields to int and see what throws the error or check which is not numeric
df[~df['Reviews'].str.isnumeric()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [31]:
### Now you have the decision of converting to thousands or droping the record completely
## But first lets make a copy of the dataset and work on the copy from now on
df_copy=df.copy()

In [32]:
#### Drop just that row from the dataset
df_copy=df_copy.drop(index=[10472])

###
df_copy[~df_copy['Reviews'].str.isnumeric()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [33]:
#### Convert the reviews feature to integer
df_copy['Reviews']=df_copy['Reviews'].astype(int)

In [34]:
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            10840 non-null  str
 5   Installs        10840 non-null  str
 6   Type            10839 non-null  str
 7   Price           10840 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 1.2 MB

In [35]:
#### Handling the Size feature next
### Size has both M-Megabyte and k-Kilobyte. Hence we need to convert to one particular datatype 
df_copy['Size'].unique()

<StringArray>
[  '19M',   '14M',  '8.7M',   '25M',  '2.8M',  '5.6M',   '29M',   '33M',
  '3.1M',   '28M',
 ...
  '467k',  '157k',   '44k',  '676k',   '67k',  '552k',  '885k', '1020k',
  '582k',  '619k']
Length: 461, dtype: str

##### Thought Process: Cleaning the Size Column

`Step 1: Inspect the raw data first`

The Google Play Store Size column typically looks like this:
['19M', '14M', '8.7M', '25M', '2.8M', '512k', '3.0M', 'Varies with device', ...]

*Key observations from this inspection:*

Values are strings, not numbers.
Sizes are mixed units: M (Megabytes) and k (Kilobytes).
There's a non-numeric category: "Varies with device" — this isn't missing data (NaN), but it's not a usable number either. You need a strategy for it.

This inspection step is critical — you should never blindly write a conversion function before knowing what all the unique values look like. Skipping this is how you get silent bugs or NaN explosions later.

`Step 2: Decide on target unit`:

*Reasoning*: You need one consistent unit to make the column numeric and comparable. You have two choices:

Convert everything to `KB (kilobytes)` — avoids fractional values since M → K is multiplying by 1024 (or 1000).
Convert everything to `MB` — keeps numbers smaller/more interpretable, but K → M creates decimals (e.g., 512k → 0.5M).

Either is valid. I'll standardize to KB here since it avoids introducing decimals from the smaller unit, but the logic is symmetric if you prefer MB.


`Step 3: Decide what to do with "Varies with device"`

This is a feature engineering decision, not just cleaning:

Option A: Convert to`NaN` and impute later (e.g., median size, or median size grouped by Category).
Option B: Create a separate binary flag column (Size_Varies = 1) before nulling it out — because "varies with device" might itself carry signal (e.g., apps with device-dependent size might behave differently, like games vs. utility apps).

I'd recommend Option B — it preserves information rather than discarding it.`

`Step 4: Write the conversion function`

In [36]:
def convert_size(size):
    if size == 'Varies with device':
        return np.nan
    elif size.endswith('M'):
        return float(size[:-1]) * 1024   # MB -> KB
    elif size.endswith('k'):
        return float(size[:-1])          # already in KB
    else:
        return np.nan  # catch any unexpected format

`Why write it as a function with explicit branches instead of a one-liner regex replace?`

It's easier to read and debug.
The else: return np.nan branch acts as a safety net — if the dataset has some unexpected format you didn't anticipate during Step 1, it won't crash your pipeline; it'll just surface as a NaN you can investigate.

In [ ]:
### Step 5: Apply it and create the flag column first
df_copy['Size_Varies'] = (df_copy['Size'] == 'Varies with device').astype(int)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_Varies
10709,FO AIRBUS Nantes,COMMUNICATION,NaN,0,17M,100+,Free,0,Everyone,Communication,"December 14, 2017",1.0,4.1 and up,0
7735,CQ Ukraine,PRODUCTIVITY,NaN,0,9.1M,10+,Free,0,Everyone,Productivity,"June 25, 2018",1.17.0,4.1 and up,0
5319,Al-Quran (Free),BOOKS_AND_REFERENCE,4.6,218451,4.7M,"10,000,000+",Free,0,Everyone,Books & Reference,"May 20, 2018",3.2.3,4.0 and up,0
3816,Google News,NEWS_AND_MAGAZINES,3.9,877643,13M,"1,000,000,000+",Free,0,Teen,News & Magazines,"August 1, 2018",5.2.0,4.4 and up,0
6891,Philips Hue,LIFESTYLE,3.1,10006,53M,"1,000,000+",Free,0,Everyone,Lifestyle,"July 26, 2018",3.2.0,5.0 and up,0

`Why do this?`

Notice something interesting.

Originally the information was stored as text:

`Varies with device`

But that text really represents a condition:

Does the app have a fixed size?

Yes or No.

By creating Size_Varies, you've transformed a text category into a binary feature (0 or 1), which is much easier for many machine learning algorithms to use.

In [42]:
### After this step you can apply conversion
df_copy['Size'] = df_copy['Size'].apply(convert_size)

In [48]:
df_copy.sample(5)
df_copy.info()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  str
 6   Type            10839 non-null  str
 7   Price           10840 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
 13  Size_Varies     10840 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 1.2 MB

In [49]:
df_copy[['Size', 'Size_Varies']].sample(10)

         Size  Size_Varies
4159  52224.0            0
9868   4505.6            0
7393   6553.6            0
2202  12288.0            0
2538  14336.0            0
1136      NaN            1
1734  18432.0            0
4965   2969.6            0
2819  19456.0            0
1053  71680.0            0

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [57]:
### Step 7: Handle the resulting missing values
df_copy['Size'].isnull().sum()

df_copy[df_copy['Size'].isnull()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Size_Varies
37,Floor Plan Creator,ART_AND_DESIGN,4.1,36639,NaN,"5,000,000+",Free,0,Everyone,Art & Design,"July 14, 2018",Varies with device,2.3.3 and up,1
42,Textgram - write on photos,ART_AND_DESIGN,4.4,295221,NaN,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",Varies with device,Varies with device,1
52,Used Cars and Trucks for Sale,AUTO_AND_VEHICLES,4.6,17057,NaN,"1,000,000+",Free,0,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device,Varies with device,1
67,Ulysse Speedometer,AUTO_AND_VEHICLES,4.3,40211,NaN,"5,000,000+",Free,0,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device,Varies with device,1
68,REPUVE,AUTO_AND_VEHICLES,3.9,356,NaN,"100,000+",Free,0,Everyone,Auto & Vehicles,"May 25, 2018",Varies with device,Varies with device,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10713,My Earthquake Alerts - US & Worldwide Earthquakes,WEATHER,4.4,3471,NaN,"100,000+",Free,0,Everyone,Weather,"July 24, 2018",Varies with device,Varies with device,1
10725,Posta App,MAPS_AND_NAVIGATION,3.6,8,NaN,"1,000+",Free,0,Everyone,Maps & Navigation,"September 27, 2017",Varies with device,4.4 and up,1
10765,Chat For Strangers - Video Chat,SOCIAL,3.4,622,NaN,"100,000+",Free,0,Mature 17+,Social,"May 23, 2018",Varies with device,Varies with device,1
10826,Frim: get new friends on local chat rooms,SOCIAL,4.0,88486,NaN,"5,000,000+",Free,0,Mature 17+,Social,"March 23, 2018",Varies with device,Varies with device,1
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,1

In [59]:
df_copy['Category'].unique()

<StringArray>
[     'ART_AND_DESIGN',   'AUTO_AND_VEHICLES',              'BEAUTY',
 'BOOKS_AND_REFERENCE',            'BUSINESS',              'COMICS',
       'COMMUNICATION',              'DATING',           'EDUCATION',
       'ENTERTAINMENT',              'EVENTS',             'FINANCE',
      'FOOD_AND_DRINK',  'HEALTH_AND_FITNESS',      'HOUSE_AND_HOME',
  'LIBRARIES_AND_DEMO',           'LIFESTYLE',                'GAME',
              'FAMILY',             'MEDICAL',              'SOCIAL',
            'SHOPPING',         'PHOTOGRAPHY',              'SPORTS',
    'TRAVEL_AND_LOCAL',               'TOOLS',     'PERSONALIZATION',
        'PRODUCTIVITY',           'PARENTING',             'WEATHER',
       'VIDEO_PLAYERS',  'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION']
Length: 33, dtype: str

### Step 1: What's the problem we're trying to solve?

Suppose your dataset looks like this:

App	Category	Size_KB
WhatsApp	Communication	25000
Gmail	Communication	30000
Zoom	Communication	NaN
Candy Crush	Games	85000
Subway Surfers	Games	90000
Temple Run	Games	NaN

Notice that Zoom and Temple Run have missing sizes.

A simple approach would be:

```python
df['Size_KB'] = df['Size'].fillna(0)
```

This fills every missing value with the overall median.

But is that reasonable?

Communication apps tend to be much smaller than games. Giving both the same replacement value could distort the data.

A better idea is:

`Fill each missing size using the median size within its own category.`

In [63]:
df_copy.groupby('Category')

In [65]:
df_copy['Size'] = df_copy['Size'].fillna(
    df_copy.groupby('Category')['Size'].transform('median')
)

In [70]:
df_copy.info()
df_copy['Size'].isnull().sum()

<class 'pandas.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            10840 non-null  float64
 5   Installs        10840 non-null  str
 6   Type            10839 non-null  str
 7   Price           10840 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10840 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10838 non-null  str
 13  Size_Varies     10840 non-null  int64
dtypes: float64(2), int64(2), str(10)
memory usage: 1.2 MB

np.int64(0)

- This is the general pattern for any "messy mixed-unit string column": inspect unique values → choose a target unit → explicitly decide how to treat non-numeric categories → write an explicit conversion function with a safety-net else branch → verify → impute.