In [7]:
import pandas as pd
import numpy as np

# Create a sample healthcare dataset
data = {
    "age": [25, 32, 47, 51, 62, 23, 40, 36, 29, 55],
    "blood_pressure": [120, 130, 140, 135, 150, 110, 145, 138, 125, 155],
    "cholesterol": [180, 190, 210, 220, 240, 170, 230, 200, 185, 250],
    "bmi": [22.5, 24.0, 27.5, 30.0, 32.5, 21.0, 28.0, 26.5, 23.0, 31.0],
    "risk": [0, 0, 1, 1, 1, 0, 1, 0, 0, 1]  # 0 = low risk, 1 = high risk
}

df = pd.DataFrame(data)

df

   age  blood_pressure  cholesterol   bmi  risk
0   25             120          180  22.5     0
1   32             130          190  24.0     0
2   47             140          210  27.5     1
3   51             135          220  30.0     1
4   62             150          240  32.5     1
5   23             110          170  21.0     0
6   40             145          230  28.0     1
7   36             138          200  26.5     0
8   29             125          185  23.0     0
9   55             155          250  31.0     1

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             10 non-null     int64
 1   blood_pressure  10 non-null     int64
 2   cholesterol     10 non-null     int64
 3   bmi             10 non-null     float64
 4   risk            10 non-null     int64
dtypes: float64(1), int64(4)
memory usage: 532.0 bytes

## Measure of Central Tendency
- Testing the central tendency of this data points using python

In [9]:
# Mean for each column
df.mean(numeric_only=True)

# Testing for a specific column
mean_blood_pressure = df["blood_pressure"].mean()
print(mean_blood_pressure)

134.8

In [10]:
# Finding the median
print(df["blood_pressure"].median())

136.5

In [11]:
# Fing the mode, the value that appears very often
print(df["blood_pressure"].mode())

0    110
1    120
2    125
3    130
4    135
5    138
6    140
7    145
8    150
9    155
Name: blood_pressure, dtype: int64

## Outliers
- Outliers are the data points that are very different from the rest of the data points
- We would create an outlier and see how the data is affected by it

In [12]:
df_with_outliers = df.copy()
df_with_outliers.loc[len(df)] = [45, 300, 500, 40, 1]

df_with_outliers

    age  blood_pressure  cholesterol   bmi  risk
0    25             120          180  22.5     0
1    32             130          190  24.0     0
2    47             140          210  27.5     1
3    51             135          220  30.0     1
4    62             150          240  32.5     1
5    23             110          170  21.0     0
6    40             145          230  28.0     1
7    36             138          200  26.5     0
8    29             125          185  23.0     0
9    55             155          250  31.0     1
10   45             300          500  40.0     1

In [13]:
df_with_outliers["blood_pressure"].mean(), df_with_outliers["blood_pressure"].median()

(np.float64(149.8181818181818), np.float64(138.0))

In [14]:
df["cholesterol"].value_counts()

cholesterol
180    1
190    1
210    1
220    1
240    1
170    1
230    1
200    1
185    1
250    1
Name: count, dtype: int64

In [15]:
df["cholesterol"].median()

np.float64(205.0)

## Mimicing a Practical Dataset to Learn the Measure of Dispersion of Data

In [16]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 120

data = {
    "age": np.random.randint(18, 65, n),
    "monthly_income": np.random.randint(1000, 10000, n),
    "spending_score": np.random.randint(1, 100, n),
    "city": np.random.choice(["Accra", "Kumasi", "Tema", "Takoradi"], n),
    "subscription_type": np.random.choice(["Basic", "Standard", "Premium"], n)

}

df = pd.DataFrame(data)

df.head()

   age  monthly_income  spending_score    city subscription_type
0   56            9996              60    Tema           Premium
1   46            3731               2   Accra          Standard
2   32            9154               1  Kumasi           Premium
3   60            6056              48    Tema             Basic
4   25            9110              12  Kumasi          Standard

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                120 non-null    int64
 1   monthly_income     120 non-null    int64
 2   spending_score     120 non-null    int64
 3   city               120 non-null    str
 4   subscription_type  120 non-null    str
dtypes: int64(3), str(2)
memory usage: 4.8 KB

In [18]:
df.describe()

              age  monthly_income  spending_score
count  120.000000      120.000000       120.00000
mean    40.666667     5718.875000        48.40000
std     13.820782     2584.101344        28.71781
min     18.000000     1197.000000         1.00000
25%     28.000000     3370.500000        24.75000
50%     41.000000     6086.000000        46.00000
75%     53.000000     7917.000000        68.25000
max     64.000000     9996.000000        99.00000

## Introduction of Missing Values on Purpose

In [19]:
# Introduce missing values randomly
for col in df.columns:
    df.loc[df.sample(frac=0.1).index, col] = np.nan

df.isnull().sum()

age                  12
monthly_income       12
spending_score       12
city                 12
subscription_type    12
dtype: int64

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                108 non-null    float64
 1   monthly_income     108 non-null    float64
 2   spending_score     108 non-null    float64
 3   city               108 non-null    str
 4   subscription_type  108 non-null    str
dtypes: float64(3), str(2)
memory usage: 4.8 KB

### Handling Missing Values
# Dropping the missing values
```python
df = df.dropna()
df.info()
```
# Imputing the missing values
```python
df["monthly_income"].fillna(df["monthly_income"].mean(), inplace=True)
```
- Numeric columns
Rule:
- Use *MEAN* -> If the data is *symmetric* and *normally distributed*
- Use *MEDIAN* -> If the data is *skewed*

- Use *MODE* -> If the data is *categorical*

In [31]:
## Filling the dataset replacing null values with the mean since generated data seem symmetricl
df.isnull().sum()

df["age"] = df["age"].fillna(df["age"].mean())
df["monthly_income"] = df["monthly_income"].fillna(df["monthly_income"].mean())
df["spending_score"]=df["spending_score"].fillna(df["spending_score"].median())


df.isnull().sum()

age                   0
monthly_income        0
spending_score        0
city                 12
subscription_type    12
dtype: int64

In [38]:
## Filling Categorical Columns with Mode
df["city"].mode()
df["subscription_type"].mode()

df["city"] = df["city"].fillna(df["city"].mode()[0])
df["subscription_type"] = df["subscription_type"].fillna(df["subscription_type"].mode()[0])

df.isnull().sum()

age                  0
monthly_income       0
spending_score       0
city                 0
subscription_type    0
dtype: int64

In [40]:
df.describe(include="all")

df["monthly_income"].mean(), df["monthly_income"].median()

(np.float64(5745.75), np.float64(5745.75))

In [42]:
## Exaggrating the situation for monthly income with outliers to see how it affects the mean & median
df_extreme = df.copy()
df_extreme.loc[0, "monthly_income"] = 100000 #extreme outlier

df_extreme["monthly_income"].mean(), df_extreme["monthly_income"].median()

(np.float64(6495.783333333334), np.float64(5745.75))